export GROUP_NAME="sg-1234567890abcdef0"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=tcp,FromPort=22,ToPort=22,IpRanges="[{CidrIp=0.0.0.0/0,Description='SSH'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=tcp,FromPort=443,ToPort=443,IpRanges="[{CidrIp=0.0.0.0/0,Description='HTTPS'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=tcp,FromPort=80,ToPort=80,IpRanges="[{CidrIp=0.0.0.0/0,Description='HTTP'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=tcp,FromPort=21114,ToPort=21119,IpRanges="[{CidrIp=0.0.0.0/0,Description='RustDesk Server'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=udp,FromPort=21116,ToPort=21116,IpRanges="[{CidrIp=0.0.0.0/0,Description='RustDesk Server'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=tcp,FromPort=2112,ToPort=2112,IpRanges="[{CidrIp=0.0.0.0/0,Description='Reverse SSH'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=udp,FromPort=1194,ToPort=1194,IpRanges="[{CidrIp=0.0.0.0/0,Description='OpenVPN'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=tcp,FromPort=8080,ToPort=8080,IpRanges="[{CidrIp=0.0.0.0/0,Description='8080'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=udp,FromPort=3128,ToPort=3128,IpRanges="[{CidrIp=0.0.0.0/0,Description='Squid HTTP'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=udp,FromPort=3129,ToPort=3129,IpRanges="[{CidrIp=0.0.0.0/0,Description='Squid HTTPS'}]"
aws ec2 authorize-security-group-ingress --group-id $GROUP_NAME --ip-permissions IpProtocol=udp,FromPort=51820,ToPort=51820,IpRanges="[{CidrIp=0.0.0.0/0,Description='WireGuard'}]"
